-- Generated by Oracle SQL Developer Data Modeler 4.0.1.836
--   at:        2016-08-19 11:11:54 CEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g




CREATE TABLE img_offline
  (
    id_img_off       SERIAL PRIMARY KEY,
    path             VARCHAR (511 ) NOT NULL ,
    text_off         VARCHAR (1023 ) NOT NULL ,
    color_text       SMALLINT NOT NULL ,
    color_background SMALLINT NOT NULL ,
    color_edge       SMALLINT NOT NULL
  ) ;

CREATE TABLE img_online
  (
    id_img_on        SERIAL PRIMARY KEY,
    path             VARCHAR (511 ) NOT NULL ,
    name             VARCHAR (255 ) NOT NULL ,
    FUNCTION         VARCHAR (255 ) NOT NULL ,
    color_text       SMALLINT NOT NULL ,
    color_background SMALLINT NOT NULL ,
    color_edge       SMALLINT NOT NULL
  ) ;

CREATE TABLE mes_offline
  (
    id_mes_off SERIAL PRIMARY KEY,
    type BLOB NOT NULL ,
    text            VARCHAR (1023 ) NOT NULL ,
    shown           CHAR (1) ,
    page_to_popup   VARCHAR (255 ) ,
    LINK            VARCHAR (255 ) ,
    show_after_time INTEGER
  ) ;

CREATE TABLE mes_online
  (
    id_mes_on SERIAL PRIMARY KEY,
    type BLOB NOT NULL ,
    text            VARCHAR (1023 ) NOT NULL ,
    shown           CHAR (1) ,
    page_to_popup   VARCHAR (255 ) ,
    LINK            VARCHAR (255 ) ,
    show_after_time INTEGER
  ) ;

CREATE TABLE messages
  (
    id_mes    SERIAL PRIMARY KEY,
    prectena  TINYINT (1 ) NOT NULL,
    img       VARCHAR (100 ),
    name      VARCHAR (50 ) NOT NULL,
    message   VARCHAR (1024 ) NOT NULL ,
    time DATETIME NOT NULL
  ) ;

CREATE TABLE notifications
  (
    id_noti      SERIAL PRIMARY KEY,
    name_of_user VARCHAR (100 ) ,
    type         VARCHAR (255 ) NOT NULL ,
    name         VARCHAR (255 ) NOT NULL ,
    text_od_noti VARCHAR (1024 ) NOT NULL ,
    time         DATETIME NOT NULL,
    link_name    VARCHAR (20 ) ,
    link         VARCHAR (255 )
  ) ;

CREATE TABLE person
  (
    id_person  SERIAL PRIMARY KEY,
    password   VARCHAR (255 ) NOT NULL ,
    firstname  VARCHAR (50 ) NOT NULL ,
    lastname   VARCHAR (50 ) NOT NULL ,
    function   VARCHAR (50 ) NOT NULL,
    email      VARCHAR (255 ) NOT NULL ,
    phone_num  VARCHAR (20 ) NOT NULL ,
    web_page   VARCHAR (255 ) NOT NULL ,
    firm       VARCHAR (100 ) NOT NULL,
    address    VARCHAR (255 ) NOT NULL ,
    city       VARCHAR (50 ) NOT NULL ,
    psc        VARCHAR (6 ) NOT NULL ,
    ic         VARCHAR (10 ) NOT NULL ,
    dic        VARCHAR (20 ) NOT NULL ,
    noti_email TINYINT (1) NOT NULL ,
    newsletter TINYINT (1) NOT NULL
  ) ;


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             7
-- CREATE INDEX                             0
-- ALTER TABLE                              7
-- CREATE VIEW                              0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
